name: Android CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Fix Android Build Tools File Names
      run: |
        cd $ANDROID_HOME/build-tools/33.0.0
        mv d8 dx
        cd lib
        mv d8.jar dx.jar
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
